name: Run unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18 
    
    - name: Install Task
      uses: arduino/setup-task@v1

    - name: Run integration tests
      run: task integration-tests
